# Use the official Alpine image
FROM alpine:latest

# Install netcat (for listening on the server side)
RUN apk --no-cache add netcat-openbsd

# Set the working directory inside the container
WORKDIR /usr/src/app

# Set the default command to run the server script
CMD ["sh", "/usr/src/app/server.sh"]
